<?php

namespace App\Http\Controllers;

abstract class Controller
{
    protected $ruangan = [
        'Ruang' => [
            'Tulip',
            'Dahlia',
            'Teratai',
            'Hd',
            'Endos',
            'Gudang Aset',
            'Ipsrs L1',
            'Ipsrs L2 (sanitasi)',
            'Laundry',
            'Flam',
            'Anggrek',
            'Peri',
            'Vk',
            'Chry',
            'Gizi',
            'Boige',
            'Edelweis',
            'Radiologi',
            'Cssd',
            'Ok',
            'Depo Ok',
            'Icu',
            'Bank Darah',
            'Lab',
            'Apotek',
            'Loket Igd',
            'Igd',
            'Igd Ponek',
            'Kasir',
        ],

        'Poli' => [
            'Fisioterapi',
            'Tbk',
            'Jantung',
            'Jiwa',
            'Beda Tulang',
            'Visiti',
            'Mata',
            'Loke Pendaftaran',
            'Bedah',
            'Kandungan',
            'Saraf',
            'Poli Dalam',
            'Gigi Spesialis',
            'Pengaduan',
            'Rm L1',
            'Mini Pc Panggilan Pasien',
            'Apm',
            'Kordi Rwj',
            'Gizi',
            'Anak',
            'Tht',
            'Gigi Umum',
            'Umum',
            'Kulit',
            'Rm L2',
        ],

        'Non-Pelayanan' => [
            'Ambulance',
            'Jenazah',
            'Direktur',
            'Bpjs',
            'Keuangan',
            'Umpeg',
            'Yanmed',
            'It',
            'Pkrs',
            'Penjunjang',
            'Keperawatan',
            'Perencanaan',
        ],
    ];
}
